# ***Importing the dataset:***

In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload("Countries.csv")

# ***Reading data from the file:***

In [ ]:
filepath = "/content/Countries.csv/Countries.csv"
df = pd.read_csv(filepath)
print(df)

                country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]

# ***Overviewing the data of first 5 rows of the dataset:***

In [ ]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

# ***Overviewing the data for last 5 rows of the dataset:***

In [ ]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

# ***Calulating the total rows x columns:***

In [ ]:
df.shape

(194, 64)

# ***Overviewing every columns in the dataset:***

In [ ]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

# ***Extracting info of all the columns with their non-null count & dtype for each:***

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

# ***Extracting the Statistical Data for certain columns:***

In [ ]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

# ***Returning the type of data stored in each column:***

In [ ]:
df.dtypes

country              object
country_long         object
currency             object
capital_city         object
region               object
                     ...
democracy_score     float64
democracy_type       object
median_age          float64
political_leader     object
title                object
Length: 64, dtype: object

# ***Extracts the sum of all the null values for each individual columns:***

In [ ]:
df.isnull().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

# ***Counting total number of unqiue values in the columns:***

In [ ]:
df.nunique()

country             194
country_long        194
currency            142
capital_city        194
region               22
                   ...
democracy_score     146
democracy_type        5
median_age          143
political_leader    187
title                17
Length: 64, dtype: int64

# ***Displaying the random data of any 5 rows:***

In [ ]:
df.sample(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.9589,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.4000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.0,...,12668,10.5263,0,12668,0.00,0.00,Unknown,16.3,Lionel Aingimea,President
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,...,2388992,15.3846,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President

# ***Calculating the number of countries in each continent:***

In [ ]:
df.value_counts("continent")

continent
Africa      54
Asia        47
Europe      44
Americas    35
Oceania     14
Name: count, dtype: int64

# ***Some observations that I encountered while analyzing the dataset:***


* **Africa has the most amounts of countries.**
* **52 countries use currency of other country**
* **The birth_rate is averagely ~127% greater than the death rate**
* **According to the dataset, every country in the world now has the access to the electricity**
* **Political leaders of 7 countries are not defined(null)**
* **Rwanda has the highest percentage of womens in their parliament - 61.08**
* **Monanco has highest median age while Niger has lowest.**
* **Japan & Korea has the highest life expenctancy of 84**

# ***Extra commands for observations:***

In [ ]:
max = df['median_age'].argmax()
max_1 = df['country'].iloc[max]
print(max_1)
min = df['median_age'].argmin()
min_1 = df['country'].iloc[min]
print(min_1)

Monaco
Niger

In [ ]:
index = df["life_expectancy"].argmax()
print(index)

83

In [ ]:
index = df["women_parliament_seats_pct"].argmax()
country = df["country"].iloc[index]
print(country)

Rwanda

In [ ]:
df["birth_rate"].describe()

count    194.000000
mean      19.193593
std        9.750348
min        5.100000
25%       10.650000
50%       16.884000
75%       27.242250
max       45.293000
Name: birth_rate, dtype: float64

In [ ]:
df["death_rate"].describe()

count    194.000000
mean       8.757495
std        3.443153
min        1.311000
25%        6.600000
50%        8.090000
75%        9.989250
max       21.700000
Name: death_rate, dtype: float64

In [ ]:
df["electricity_access_pct"].isnull().sum()

np.int64(0)